== Preamble

=== Scope

This standard replaces <<ANZ4819>> but also provides guidance on aspects of addressing not covered by it, so this standard's scope then is a superset of <<ANZ4819>>'s.

Scope from <<ANZ4819>>:

a. assigning addresses;
b. naming roads and localities;
c. recording and mapping the related information; and
d. signage related to the above.

Additional scope is able to be catered for here due to the presence of the <<ADDRESS-MODEL>> which is the mandated information model for address data exchange in Australia and New Zealand.

Additional scope:

[start=5]
a. validating address information
b. sharing address information
c. joining address information to other information

=== Objective

The goals of this Standard are

1. to specify requirements for assigning addresses that can be readily and unambiguously identified and located
2. to create information representations of addresses that can be identified, understood and reused with maximum information completeness and minimum ambiguity

In order to achieve these goals, the objectives of the Standard are that:

a. Addresses are uniquely and clearly identified.
b. Roads or other primary means of access are uniquely identified and addresses' references to them are unambiguous
c. The total set of address parts, including locality, access object, numbering and sub-address elements enables addressed objects to be readily located.
d. Address information is shown to be able to be created in accordance with the ISCM ANZ Address Model
e. Address information enables addressed objects to be readily located.
f. Signage enables assigned addresses to be readily identified and located.

The Standard aims to keep addresses as simple as possible to enable their ready application and consistent information structure and style across jurisdictions. All matters pertaining to address information allowances are handled by <<ADDRESS-MODEL>>.

=== Application

==== Intended Audience

The Standard outlines various roles related to the use of address information and the tasks undertaken by holders of those roles. It is intended primarily for use by any organisation or person that is called on to act in one, or many, of those roles within an Australian or New Zealand jurisdiction.

Use of the standard is aimed at helping those acting in the roles to fulfil their custodial responsibility for the ongoing maintenance, accuracy and quality of addresses and the exchange of addressing information in a manner that is consistent across jurisdictions.

==== Retrospective application - Existing addresses

This standard is intended to apply to all roles and tasks relevant to addresses within the Intended Audience and the remediation of existing addresses is one of those tasks.

==== Data specification partially in scope

This Standard depends on the use of <<ADDRESS-MODEL>> for address information validation and exchange but does not specify detailed data requirements nor imply a database schema for the storage or internal use, within a jurisdiction, of address information.

This Standard also depends on the set of ICSM vocabularies (see the https://www.icsm.gov.au[ICSM Vocabulary Register]) to provide specific values for information model object categorisation and, in some cases, object values for <<ADDRESS-MODEL>> and its model dependencies.

==== Cooperation between agencies

Effective address information sharing and use across agencies depends on the faithful implementation of a shared information model, for which this Standard depends on <<ADDRESS-MODEL>>. This Standard aims to provide role and task guidance around the use of that model, its supporting vocabularies and addresses in general to assist with its faithful implementation.

===== Application to Indigenous addressing

Within Indigenous communities, roads shall be named and address sites numbered in accordance with this Standard.

Indigenous address elements and the use of Indigenous languages within address information is catered for within <<ADDRESS-MODEL>>.

==== Application to private communities and towns

A private community or town, such as a retirement village or mining town, shall be addressed in terms of this Standard.

Extended forms of addressing, such as subaddressing, is catered for within <<ADDRESS-MODEL>>.

=== Normative References

Multiple Australia/New Zealand Standards, information models and other documents are referred to by this Standard. References from normative sections of this document are themselves considered to be normative, unless they are specifically indicated as being informative.

References from informative sections, however made, are informative.

=== Definitions

==== Imperative terminology

The keywords MAY, MUST, MUST NOT, and SHOULD in this document are to be interpreted as described in <<BCP14>> when, and only when, they appear in all capitals, as shown here.

==== Glossary

Definitions of specialised terms used in this Standard are taken from ICSM Vocabularies and models, in particular:

// TODO: make Addressing Glossary PID
* https://linked.data.gov.au/def/addr-glossary[Addressing Glossary]
* <<ADDRESS-MODEL>>
* vocabularies supporting <<ADDRESS-MODEL>>
** See the model's https://linked.data.gov.au/def/addr#_vocabularies[Vocabularies Section]

See the https://www.icsm.gov.au[ICSM Vocabulary Register] for all ICSM vocabularies.

// TODO: Fix Geocode PID
Where specialised terms defined in the above resources are used, they are hyperlinked to their definition online, for example the term https://linked.data.gov.au/def/addr/Geocode[geocode].

=== Namespaces

// TODO: Add IRI to Glossary
Namespaces, in this document's context, are managed http://linked.data.gov.au/def/addrr-glossary/IRI[IRIs] which allow further IRIs to be created within their scope. Namespaces are allocated to macro data objects and provide IRIs for all the micro data objects within that object.

For example, the IRI for the <<ADDR2024, Address Model>> is `+https://linked.data.gov.au/def/addr+` and the namespace of `+https://linked.data.gov.au/def/addr/+` (the Address Model's IRI + `/`) allows for IRIs to be created for elements within the model such as one for the `Geocode` class which is `+https://linked.data.gov.au/def/addr/Geocode+`.

When used in some forms of data and human-readable text, IRIs can either be written in full or in a shortened form using prefixes for known namespace. For example, the `Geocode` mentioned above can be written in full like this:

`+https://linked.data.gov.au/def/addr/Geocode+`

or in prefixed form with the prefix `addr` for the namespace `+https://linked.data.gov.au/def/addr/+` like this:

`addr:Geocode`

See the table below for namespace prefixes used in this Standard.

==== Prefixes

The prefixed namespaces used in this document are:

// TODO: tidy prefixes as used/not used in this doc
[width=100%, frame=none, grid=none, cols="1,5,4"]
|===
|Prefix | Namespace | Description

| `*addr*` | `*+https://linked.data.gov.au/def/addr/+*` | <<ADDR2024, ICSM's  Address Model>>
| `*addrcm*` | `*+https://linked.data.gov.au/def/addr-cm/+*` | *This Document*
| `*addrg*` | `*+https://linked.data.gov.au/def/addr-glos/+*` | https://linked.data.gov.au/def/addr-glos/[Addressing Glossary]
| `addreq` | `+https://linked.data.gov.au/def/addrcm-req/+` | https://linked.data.gov.au/def/addrcm-req[Address Creation & Maintenance Requirements Vocabulary]
| `als` | `+https://linked.data.gov.au/def/address-lifecycle-stage-type/+` | https://linked.data.gov.au/def/lifecycle-stage-types[Address Lifecycle Stage Types vocabulary]
| `apt` | `+https://linked.data.gov.au/def/address-part-type/+` | https://linked.data.gov.au/def/addr-part-types[Address Part Types vocabulary]
| `asgsed3` | `+https://linked.data.gov.au/dataset/asgsed3/+` | https://linked.data.gov.au/dataset/asgsed3[Australian Statistical Geographies Standard Dataset, Release 3]
| `cn` | `+https://linked.data.gov.au/def/cn/+` | https://linked.data.gov.au/def/cn[Compound Naming Model]
| `ex` | `+http://example.com/+` | Generic examples
| `geo` | `+http://www.opengis.net/ont/geosparql#+` | https://docs.ogc.org/is/22-047r1/22-047r1.html[OGC GeoSPARQL]
| `gt` | `+http://www.opengis.net/ont/geocode-types/+` | https://linked.data.gov.au/def/geocode-types[Geocode types vocabulary]
| `ls` | `+https://linked.data.gov.au/def/lifecycle/+` | https://linked.data.gov.au/def/lifecycle[Lifecycle Model]
| `owl` | `+http://www.w3.org/2002/07/owl#+` | https://www.w3.org/TR/owl2-overview/[Web Ontology Language ontology]
| `rdf` | `+http://www.w3.org/1999/02/22-rdf-syntax-ns#+` | https://www.w3.org/TR/rdf-concepts/[The RDF Concepts Vocabulary]
| `rdfs` | `+http://www.w3.org/2000/01/rdf-schema#+` | https://www.w3.org/TR/rdf12-schema/[RDF Schema ontology]
| `sdo` | `+https://schema.org/+` | https://schema.org[schema.org model]
| `skos` | `+http://www.w3.org/2004/02/skos/core#+` | https://www.w3.org/TR/skos-reference/[Simple Knowledge Organization System (SKOS) ontology]
| `time` | `+http://www.w3.org/2006/time#+` | https://www.w3.org/TR/owl-time/[Time Ontology in OWL]
| `xsd` | `+http://www.w3.org/2001/XMLSchema#+` | https://www.w3.org/TR/xmlschema-2/[XML Schema Definitions ontology]
|===
