[[AnnexB]]
== Annex B: Identifiers

_This section is normative_

Addressing information created in conformance with this standard _MUST_ use identifiers that meet the following criteria:

1. Interpretable as IRIs, according to <<RFC3987, RFC3987>>
    * except where information is wholly nested within another object identified with an IRI, in which case local identifiers may be used
2. Issued via a system- and organisation-independent mechanism designed for long-term identifier stability and operation

Identifiers for addressing information that meet these criteria _MAY_ be used by implementing jurisdictions independently of one another or in a coordinated manner. Advice from the https://www.linked.data.gov.au/[Australian Government Linked Data Working Group] _SHOULD_ be sought regarding technical aspects of these sorts of identifiers.

=== Identifiers per Class

Addressing information generated by processes conforming to this standard _MUST_ conform to the Address Model <<ADDR2024, ADDR2024>>. Information conforming to that model comprises instances of many different _classes_ of object, such as `Address`, `Addressable Object`, `Geocode`, `Concept` and valid identifiers must be used for all of them.

=== Local Identifiers for nested objects

IRIs must be used for all instances of classes and predicates required by the Address Model except for objects wholly nested within other objects identified with an IRI and where the nested object need never be referred to independently of the containing object.

For example the `Compound Name` object of type `Street First Number` with value "72" within the address `72 Yundah St, Shorncliffe, QLD` is relevant only to that address, so it _MAY_ be identified with a local identifier.

In <<RDF, RDF>> data in the <<TTL, Turtle>> format, the object with value "72" that is nested within an `Address` with IRI `+<http://example.com/address/x>+` may be identified using a Blank Node like this:

[source,turtle]
----
<http://example.com/address/x>
    a addr:Address ;
    sdo:hasPart [
        a cn:CompoundName ;
        sdo:additionalType apt:numberFirst ;
        rdf:value 72
    ] ,
    # ... other parts of the address
.
----

In the example above, the `Compound Name` object within `[...]` cannot be referenced outside its relation to the `Address` object.

=== Multiple identifier sources

Identifiers for objects in each of the Address Model's classes need not all come from the same system/owner. For example, a jurisdiction may create an identifier for an `Address`, individual parts of which are categorised according to the https://linked.data.gov.au/def/addr-part-types[Address Part Types] vocabulary which uses `+https://linked.data.gov.au/+`-based IRIs issued by the https://www.linked.data.gov.au/[Australian Government Linked Data Working Group].